Mysite3/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blog.views import index
urlpatterns = [
    # Examples:
    url(r'^$', 'blog.views.index', name='blog'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^blog/',include('blog.urls',namespace='blog')),
    url(r'(?P<article_id>\d)/$','blog.views.show',name='detail'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/',include('account.urls',namespace='account')),
    url(r'^pwd_reset/',include('password_reset.urls',namespace='pwd_reset',app_name='pwd_reset')),
    url(r'^article/',include('article.urls',namespace='article',app_name='article')),
]

article/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^article_column/$',views.article_column,name='article_column'),
    url(r'^rename_column/$',views.rename_article_column,name='rename_column'),
    url(r'^del_column/$',views.del_article_column,name='del_column'),
]

blog/urls.py
from django.conf.urls import url,include
from .views import index

urlpatterns = [
    url(r'^$','blog.views.index',name='blog_title'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class ArticleColumn(models.Model):
    user = models.ForeignKey(User,related_name='article_column')
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column

article/forms.py
from .models import ArticleColumn
from django import forms

class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('column',)

article/views.py
from django.shortcuts import render
from django.views.decorators.http import require_POST
from .models import ArticleColumn
from django.contrib.auth.decorators import login_required
from .forms import ArticleColumnForm
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
# Create your views here.

@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method=='GET':
        columns = ArticleColumn.objects.filter(user=request.user)
        columns_form = ArticleColumnForm()
        return render(request,'article/column/article_column.html',{'columns':columns,'columns_form':columns_form})

    if request.method == 'POST':
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id,column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user,column=column_name)
            return HttpResponse('1')

@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST['column_name']
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse('1')
    except:
        return HttpResponse('0')

@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('2')

templates/article/column/article_column.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
<div>
    <p class="text-right"><button id='add_column' onclick="add_column()" class="btn btn-primary">add column</button></p>
    <table class="table table-hover">
        <tr>
            <td>序号</td> 
            <td>栏目名称</td>
            <td>操作</td>
        </tr>
        {% for column in columns %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ column.column }}</td>
            <td>
            <a name="edit" href="javascript:" onclick="edit_column(this,{{ column.id }})"><span class="glyphicon glyphicon-pencil"></span> </a>
            <a name="delete" href="javascript:" onclick="del_column(this,{{ column.id }})"><span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span></a>
            </td>
        </tr>
        {% empty %}
        <p>这么懒，还没有设置栏目</p>
        {% endfor %}
    </table>
</div>
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src='{% static "js/layer.js" %}'></script>
<script type="text/javascript">
function add_column(){
    var index = layer.open({
	type:1,
	skin:"layui-layer-rim",
	area: ["400px", "200px"],
	title: "新增栏目",
	content: '<div class="text-center" style="margin-top:20px"><p>请输入新的栏目名称</p><p>{{columns_form.column}}</p></div>',
	btn:['确定', '取消'],
	yes: function(index, layero){
	    column_name = $('#id_column').val();
	    $.ajax({
		url:'{% url "article:article_column" %}',
		type:'POST',
		data:{"column":column_name},
		success:function(e){
		    if(e=="1"){
		    parent.location.reload();
		    layer.msg("good");
		    }else{
		        layer.msg("此栏目已有，请更换名称")
		    }
		},
	    });
	},
	btn2: function(index, layero){
	layer.close(index);
	}
    });
}

function edit_column(the,column_id){
    var name = $(the).parents('tr').children('td').eq(1).text();
    var index = layer.open({
        type:1,
        skin:'layui-layer-rim',
        title:'编辑栏目',
        area:['400px','200px'],
        content:'<div class="text-center" style="margin-top:20px"><p>请编辑的栏目名称</p><p><input type="text" id="new_name" value="'+name+'"></p></div>',
        btn:['确定','取消'],
        yes: function(index,layero) {
            new_name = $("#new_name").val();
            $.ajax({
                url:'{% url 'article:rename_column' %}',
                type: 'POST',
                data: {'column_id':column_id,'column_name':new_name},
                success:function(e){
                    if(e=='1'){
                        parent.location.reload();
                        layer.msg('good');
                    }else{
                        layer.msg('新的名称没有保存，修改失败。')
                    }
                },
                });
        },
        });
}

function del_column(the,column_id) {
    var name = $(the).parents('tr').children('td').eq(1).text();
    layer.open({
        type:1,
        skin:'layui-layer-rim',
        area: ['400px','200px'],
        title: '删除栏目',
        content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除{'+name+'}栏目</p></div>',
        btn:['确定','取消'],
        yes: function(){
        $.ajax({
            url: '{% url "article:del_column" %}',
            type:'POST',
            data:{'column_id':column_id},
            success: function(e){
                if(e=='1'){
                    parent.location.reload();
                    layer.msg('has been deleted.');
                }else{
                    layer.msg('删除失败');
            }
                },
            })
    },
        });

}

</script>
{% endblock %}