Mysite3/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blog.views import index
urlpatterns = [
    # Examples:
    url(r'^$', 'blog.views.index', name='blog'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^blog/',include('blog.urls',namespace='blog')),
    url(r'(?P<article_id>\d)/$','blog.views.show',name='detail'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/',include('account.urls',namespace='account')),
    url(r'^pwd_reset/',include('password_reset.urls',namespace='pwd_reset',app_name='pwd_reset')),
    url(r'^article/',include('article.urls',namespace='article',app_name='article')),
]

account/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$',auth_views.login,name='user_login'),
    url(r'^$', auth_views.login, name='user_login'),
    #url(r'^logout/$',auth_views.logout,name='user_logout'),
    url(r'^logout/$',auth_views.logout,{'template_name':'account/logout.html'},name='user_logout'),
    url(r'^register/$',views.register,name='user_register'),
    url(r'^password_change/$',auth_views.password_change,{'post_change_redirect':'/account/password_change_done'},name='password_change'),
    url(r'^password_change_done/$',auth_views.password_change_done,name='password_change_done'),

    url(r'^password_reset/$',auth_views.password_reset,{'template_name':'account/password_reset_form.html',
        'email_template_name':'account/password_reset_email.html',
        'subject_template_name':'account/password_reset_subject.txt',
        'post_reset_redirect':'/account/password_reset_done'},name='password_reset'),
    url(r'^password_reset_done/$',auth_views.password_reset_done,{'template_name':'account/password_reset_done.html'},name='password_reset_done'),
    url(r'^password_reset_confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',auth_views.password_reset_confirm,
        {'template_name':'account/password_reset_confirm.html','post_reset_redirect':'/account/password_reset_complete'},
        name='password_reset_confirm'),
    url(r'^password_reset_complete/$',auth_views.password_reset_complete,
        {'template_name':'account/password_reset_complete.html'},name='password_reset_complete'),
    url(r'^my_information/$',views.myself,name='my_information'),
    url(r'^edit_my_information/$',views.myself_edit,name='edit_my_information'),
    url(r'^my_image/$',views.my_image,name='my_image'),
]

article/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^article_column/$',views.article_column,name='article_column'),
    url(r'^rename_column/$',views.rename_article_column,name='rename_column'),
    url(r'^del_column/$',views.del_article_column,name='del_column'),
]

blog/urls.py
from django.conf.urls import url,include
from .views import index

urlpatterns = [
    url(r'^$','blog.views.index',name='blog_title'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    {% include 'header.html' %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% for L in article %}
        <li style="position:relative; left:400px;"><a href="{{ L.id }}">{{ L }}</a></li>
    {% endfor %}
    {% include 'footer.html' %}
    {% block javascritp %}{% endblock %}
</body>
</html>

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right www.cgs.com</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com"><img src="/static/images/0.jpg" width="100px" height="80px" ></a>
        </div>
        <div>
            <ul class="nav nacbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a> </li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px">
                {% if user.is_authenticated %}

                <div class="dropdown" style="margin-top:8px">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown">{{ user.username }}<span class="caret"></span> </button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                            <li><a href="{% url 'account:my_information' %}">个人信息</a> </li>
                        </ul>
                </div>
                <script src="{% static 'js/jquery.js' %}"></script>
                <script src="{% static 'js/bootstrap.js' %}"></script>
                <li><a href="{% url 'account:user_logout' %}">Logout</a> </li>
                <li><a href="{% url 'article:article_column' %}">文章管理</a> </li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">LOGIN</a> </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>